// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/supabase';

const SUPABASE_URL = "https://mhwkcmvhgbdkrhtkfnxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1od2tjbXZoZ2Jka3JodGtmbnhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDEzNjQsImV4cCI6MjA2ODQxNzM2NH0.emY7lXDvCQE5h8CecaeUkOb3vfbdGzccB5NZsrMT7ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});